# Generated by Django 3.0.3 on 2020-02-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='about_me_main_image', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='aboutmeservices',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtailimages.Image'),
        ),
    ]
