# Generated by Django 3.0.3 on 2020-02-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('about_me', '0005_auto_20200210_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeservices',
            name='image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='about_services_image', to='wagtailimages.Image'),
        ),
    ]
