# Generated by Django 3.0.3 on 2020-02-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepage',
            name='image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='welcome_main_image', to='wagtailimages.Image'),
        ),
    ]
